Teleport/Models/ShoppingCart.cs
using System.Collections.Generic;
using System.Linq;

namespace Teleport.Models
{
    public class ShoppingCart
    {
        public int CustomerId { get; set; }
        public List<ShoppingCartCommodity> ShoppingCartCommodities { get; set; }

        public void AddCommodity(ShoppingCartCommodity shoppingCartCommodity)
        {
            var commodityInCart = ShoppingCartCommodities.FirstOrDefault(commodity => commodity.Commodity.Id == shoppingCartCommodity.Commodity.Id);
            if (commodityInCart == null)
            {
                ShoppingCartCommodities.Add(shoppingCartCommodity);
            }
        }

        public void RemoveCommodity(ShoppingCartCommodity shoppingCartCommodity)
        {
            var commodityInCart = ShoppingCartCommodities.FirstOrDefault(commodity => commodity.Commodity.Id == shoppingCartCommodity.Commodity.Id);
            if (commodityInCart != null)
            {
                ShoppingCartCommodities.Remove(commodityInCart);
            }
        }

        public void UpdateCommodity(ShoppingCartCommodity shoppingCartCommodity)
        {
            var commodityInCart = ShoppingCartCommodities.First(commodity => commodity.Commodity.Id == shoppingCartCommodity.Commodity.Id);

            commodityInCart.Quantity = shoppingCartCommodity.Quantity;
        }
    }
}

Teleport/Controllers/ShoppingCartController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Teleport.Models;
using Teleport.Services;

namespace Teleport.Controllers
{
    public class ShoppingCartController : BaseAuthorizeController
    {
        private readonly IShoppingCartService _shoppingCartService;

        public ShoppingCartController(IShoppingCartService shoppingCartService)
        {
            _shoppingCartService = shoppingCartService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var shoppingCart = _shoppingCartService.GetCart(CustomerId);

            return View("Index", new ShoppingCartRowsViewModel
            {
                Rows = shoppingCart.ShoppingCartCommodities.Select(commodity => new ShoppingCartCommodityRow()
                {
                    CommodityId = commodity.Commodity.Id,
                    CommodityTitle = commodity.Commodity.Title,
                    Quantity = commodity.Quantity
                }).ToList()
            });
        }

        [HttpPost]
        public async Task<ActionResult> AddCommodity(ShoppingCartCommodityOperationRequest shoppingCartCommodityOperationRequest)
        {
            await _shoppingCartService.AddCommodity(CustomerId, new ShoppingCartCommodity
            {
                Commodity = new Commodity
                {
                    Id = shoppingCartCommodityOperationRequest.CommodityId
                },
                Quantity = shoppingCartCommodityOperationRequest.Quantity
            });

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> RemoveCommodity(ShoppingCartCommodityOperationRequest shoppingCartCommodityOperationRequest)
        {
            await _shoppingCartService.RemoveCommodity(CustomerId, new ShoppingCartCommodity
            {
                Commodity = new Commodity
                {
                    Id = shoppingCartCommodityOperationRequest.CommodityId
                },
                Quantity = shoppingCartCommodityOperationRequest.Quantity
            });

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> UpdateCommodity(ShoppingCartCommodityOperationRequest shoppingCartCommodityOperationRequest)
        {
            await _shoppingCartService.UpdateCommodity(CustomerId, new ShoppingCartCommodity
            {
                Commodity = new Commodity
                {
                    Id = shoppingCartCommodityOperationRequest.CommodityId
                },
                Quantity = shoppingCartCommodityOperationRequest.Quantity
            });

            return RedirectToAction("Index");
        }
    }
}

Teleport/Views/ShoppingCart/Index.cshtml
@model ShoppingCartRowsViewModel

@{
    ViewBag.Title = "Shopping Cart";
    Layout = "_Layout";
}

<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>CommodityId</th>
                <th>CommodityTitle</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Rows.Count(); i++)
            {
            <tr>
                <td>@(i + 1)</td>
                <td>@Model.Rows[i].CommodityId</td>
                <td>@Model.Rows[i].CommodityTitle</td>
                <td>@Model.Rows[i].Quantity</td>
            </tr>
            }
        </tbody>
    </table>
</div>

AddCommodity
<form asp-action="AddCommodity" asp-controller="ShoppingCart" method="post">
    <input type="number" name="commodityId" placeholder="CommodityId">
    <input type="number" name="quantity" placeholder="Quantity">
    <input type="submit">
</form>

RemoveCommodity
<form asp-action="RemoveCommodity" asp-controller="ShoppingCart" method="post">
    <input type="number" name="commodityId" placeholder="CommodityId">
    <input type="submit">
</form>

UpdateCommodity
<form asp-action="UpdateCommodity" asp-controller="ShoppingCart" method="post">
    <input type="number" name="commodityId" placeholder="CommodityId">
    <input type="number" name="quantity" placeholder="Quantity">
    <input type="submit">
</form>