Teleport/Models/Commodity.cs
using System;

namespace Teleport.Models
{
    public class Commodity
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime ModifiedOn { get; set; }
        public string ImageName { get; set; }
    }
}

Teleport/Models/CommodityViewModel.cs
using System.Collections.Generic;
using Teleport.Controllers;

namespace Teleport.Models
{
    public class CommodityViewModel
    {
        public List<CommodityRow> Rows { get; set; }
    }
}

Teleport/Controllers/CommodityController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Teleport.Models;
using Teleport.Repository;
using Teleport.Services;

namespace Teleport.Controllers
{
    public class CommodityController : Controller
    {
        private readonly ICommodityService _commodityService;
        private readonly IImageRepository _imageRepository;

        public CommodityController(ICommodityService commodityService, IImageRepository imageRepository)
        {
            _commodityService = commodityService;
            _imageRepository = imageRepository;
        }

        public IActionResult Index()
        {
            var commodities = _commodityService.GetAllCommodities();

            var viewModel = new CommodityViewModel
            {
                Rows = commodities.Select(commodity => new CommodityRow
                {
                    Id = commodity.Id,
                    Title = commodity.Title,
                    Price = commodity.Price,
                    ImageName = commodity.ImageName
                }).OrderBy(commodity => commodity.Id).ToList()
            };

            return View("Index", viewModel);
        }

        [HttpPost]
        public IActionResult Upsert(CommodityOperationRequest request)
        {
            var commodity = new Commodity
            {
                Id = request.Id,
                Title = request.Title,
                Price = request.Price
            };
            _commodityService.UpsertCommodity(commodity);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Remove(int commodityId)
        {
            var commodity = new Commodity
            {
                Id = commodityId
            };

            _commodityService.RemoveCommodity(commodity);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult UploadImage(UploadImageDataRequest request)
        {
            _imageRepository.Upload(request);

            if (request.IsEnd)
            {
                var commodity =
                    _commodityService.GetAllCommodities()
                        .First(x => x.Id == request.Id);

                commodity.ImageName = request.ImageName;
                _commodityService.UpsertCommodity(commodity);
            }

            return RedirectToAction("Index");
        }
    }
}

Teleport/Views/Commodity/Index.cshtml
@model CommodityViewModel

@{
    ViewBag.Title = "Commodity Back Office";
    Layout = "_Layout";
}

<script type="text/javascript" src="js/imageUpload.js"></script>

<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Id</th>
                <th>Title</th>
                <th>Price</th>
                <th>Image</th>
                <th>Operation</th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Rows.Count; i++)
            {
                <tr>
                    <td>@(i + 1)</td>
                    <td>@Model.Rows[i].Id</td>
                    <td>@Model.Rows[i].Title</td>
                    <td>@Model.Rows[i].Price</td>
                    <td>
                        <label for="@Model.Rows[i].Id-image-upload">
                            <img id="@Model.Rows[i].Id-image" width="200" alt="" src="/image/@(Model.Rows[i].ImageName).jpg"/>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-image" viewBox="0 0 16 16">
                                <path d="M6.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                                <path d="M2.002 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2h-12zm12 1a1 1 0 0 1 1 1v6.5l-3.777-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062L1.002 12V3a1 1 0 0 1 1-1h12z"/>
                            </svg>
                            <input accept="image/*" id="@Model.Rows[i].Id-image-upload" name="imageData" onchange="loadFile(event, '@Model.Rows[i].Id-image');" style="display: none" type="file">
                            <input type="text" id="@Model.Rows[i].Id-image-name" name="imageNname" placeholder="Image Name"/>
                            <button class="btn btn-primary" onclick="onFilePicked(event, @Model.Rows[i].Id);">Upload</button>
                        </label>
                    </td>
                    <td>
                        <a asp-controller="Commodity" asp-action="Remove" asp-route-commodityId="@Model.Rows[i].Id">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z" />
                            </svg>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

UpsertCommodity
<form asp-action="Upsert" asp-controller="Commodity" method="post">
    <input type="text" name="Title" placeholder="Title">
    <input type="number" name="Price" placeholder="Price">
    <input type="submit">
</form>